apiVersion: v1
kind: Service
metadata:
  name: crest-svc
  labels:
    app: crest-countries
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: crest-countries
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crest-countries
  labels:
    app: crest-countries
    environment: development
spec:
  replicas: 10
  selector:
    matchLabels:
      app: crest-countries
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: crest-countries
    spec:
      volumes:
      - name: crest
        secret:
          secretName: crest-db-dsn
      containers:
      - name: crest-countries-ctr
        image: sxntana/crest-countries:nightly
        ports:
        - containerPort: 8080
        env:
        - name: CREST_ENV
          value: "development"
        - name: CREST_DB_MAX_OPEN_CONNS
          value: "25"
        - name: CREST_DB_MAX_IDLE_CONNS
          value: "25"
        - name: CREST_DB_MAX_IDLE_TIME
          value: "15m"
        volumeMounts:
        - name: crest
          mountPath: /etc/crest
          readOnly: true
      

