name: Crestcountry API pipeline
on:
  push:
    branches:
      - 'main'
      - 'develop'
jobs:
  build-setup:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
      -
        name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

  release:
    if: ${{ github.ref_name == 'main' }}
    needs: build-setup
    runs-on: ubuntu-latest
    steps:
      -
        name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/crest-countries:latest,${{ secrets.DOCKER_USERNAME }}/crest-countries:0.0-${{ github.run_number }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/crest-countries:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/crest-countries:buildcache,mode=max
          
  release-nightly:
    if: ${{ github.ref_name == 'develop' }}
    needs: build-setup
    runs-on: ubuntu-latest
    steps:
      -
        name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/crest-countries:latest-nightly,${{ secrets.DOCKER_USERNAME }}/crest-countries:0.0-${{ github.run_number }}-nightly
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/crest-countries:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/crest-countries:buildcache,mode=max